# Generated by Django 3.2.9 on 2021-11-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='articles',
            new_name='article',
        ),
    ]
